spring:
  application:
    name: kentra-cms-gyCustomer #贵阳用户项目名称
#  security:
#    user:
#      name: "admin"
#      password: "123456"
server:
  port: 8773 #贵阳用户项目端口号
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml #mybatis配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml #mybatis扫描路径及文件类型